using System.Collections.Generic;

namespace Multiverse.Globalization.Electrical;

/// <summary>
/// Provides electrical system data (voltage, frequency, plug types) for all countries.
/// </summary>
public static class ElectricalSystemHelper
{
    private static readonly Dictionary<string, ElectricalSystem> _data = InitializeData();

    internal static ElectricalSystem? GetElectricalSystemForCountry(string alpha2Code)
    {
        if (string.IsNullOrWhiteSpace(alpha2Code))
            return null;
        return _data.TryGetValue(alpha2Code.ToUpperInvariant(), out var system) ? system : null;
    }

    /// <summary>All electrical system data keyed by country alpha-2 code.</summary>
    public static IReadOnlyDictionary<string, ElectricalSystem> All => _data;

    private static Dictionary<string, ElectricalSystem> InitializeData()
    {
        return new Dictionary<string, ElectricalSystem>
        {
            // ── Asia ──────────────────────────────────────────────────────
            ["AF"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F),
            ["AM"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["AZ"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F),
            ["BH"] = new ElectricalSystem(230, 50, PlugType.G),
            ["BD"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.D, PlugType.G, PlugType.K),
            ["BT"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D, PlugType.F, PlugType.G),
            ["BN"] = new ElectricalSystem(240, 50, PlugType.G),
            ["KH"] = new ElectricalSystem(230, 50, PlugType.A, PlugType.C, PlugType.G),
            ["CN"] = new ElectricalSystem(220, 50, PlugType.A, PlugType.C, PlugType.I),
            ["CY"] = new ElectricalSystem(240, 50, PlugType.G),
            ["GE"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F),
            ["IN"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D, PlugType.M),
            ["ID"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["IR"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F),
            ["IQ"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D, PlugType.G),
            ["IL"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.H),
            ["JP"] = new ElectricalSystem(100, 50, PlugType.A, PlugType.B),
            ["JO"] = new ElectricalSystem(230, 50, PlugType.B, PlugType.C, PlugType.D, PlugType.F, PlugType.G, PlugType.J),
            ["KZ"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F),
            ["KW"] = new ElectricalSystem(240, 50, PlugType.C, PlugType.G),
            ["KG"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F),
            ["LA"] = new ElectricalSystem(230, 50, PlugType.A, PlugType.B, PlugType.C, PlugType.E, PlugType.F),
            ["LB"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D, PlugType.G),
            ["MY"] = new ElectricalSystem(240, 50, PlugType.G),
            ["MV"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D, PlugType.G, PlugType.J, PlugType.K, PlugType.L),
            ["MN"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.E),
            ["MM"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D, PlugType.F, PlugType.G),
            ["NP"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D, PlugType.M),
            ["KP"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F),
            ["KR"] = new ElectricalSystem(220, 60, PlugType.C, PlugType.F),
            ["OM"] = new ElectricalSystem(240, 50, PlugType.C, PlugType.G),
            ["PK"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D),
            ["PS"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.H),
            ["PH"] = new ElectricalSystem(220, 60, PlugType.A, PlugType.B, PlugType.C),
            ["QA"] = new ElectricalSystem(240, 50, PlugType.D, PlugType.G),
            ["SA"] = new ElectricalSystem(220, 60, PlugType.A, PlugType.B, PlugType.G),
            ["SG"] = new ElectricalSystem(230, 50, PlugType.G),
            ["LK"] = new ElectricalSystem(230, 50, PlugType.D, PlugType.G, PlugType.M),
            ["SY"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E, PlugType.L),
            ["TW"] = new ElectricalSystem(110, 60, PlugType.A, PlugType.B),
            ["TJ"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F),
            ["TH"] = new ElectricalSystem(220, 50, PlugType.A, PlugType.B, PlugType.C, PlugType.O),
            ["TL"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E, PlugType.F, PlugType.I),
            ["TR"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["TM"] = new ElectricalSystem(220, 50, PlugType.B, PlugType.F),
            ["AE"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.D, PlugType.G),
            ["UZ"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F),
            ["VN"] = new ElectricalSystem(220, 50, PlugType.A, PlugType.C, PlugType.F),
            ["YE"] = new ElectricalSystem(230, 50, PlugType.A, PlugType.D, PlugType.G),

            // ── Europe ────────────────────────────────────────────────────
            ["AL"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["AD"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["AT"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["BY"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F),
            ["BE"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.E),
            ["BA"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["BG"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["HR"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["CZ"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.E),
            ["DK"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.E, PlugType.F, PlugType.K),
            ["EE"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["FI"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["FR"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.E),
            ["DE"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["GR"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["HU"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["IS"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["IE"] = new ElectricalSystem(230, 50, PlugType.G),
            ["IT"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F, PlugType.L),
            ["LV"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["LI"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.J),
            ["LT"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["LU"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["MT"] = new ElectricalSystem(230, 50, PlugType.G),
            ["MD"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["MC"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.E, PlugType.F),
            ["ME"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["NL"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["MK"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["NO"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["PL"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.E),
            ["PT"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["RO"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["RU"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F),
            ["SM"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F, PlugType.L),
            ["RS"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["SK"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.E),
            ["SI"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["ES"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["SE"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["CH"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.J),
            ["UA"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["GB"] = new ElectricalSystem(230, 50, PlugType.G),
            ["VA"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F, PlugType.L),

            // ── Africa ────────────────────────────────────────────────────
            ["DZ"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["AO"] = new ElectricalSystem(220, 50, PlugType.C),
            ["BJ"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E),
            ["BW"] = new ElectricalSystem(230, 50, PlugType.D, PlugType.G, PlugType.M),
            ["BF"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E),
            ["BI"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E),
            ["CV"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F),
            ["CM"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E),
            ["CF"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E),
            ["TD"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.D, PlugType.E, PlugType.F),
            ["KM"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E),
            ["CG"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.E),
            ["CD"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.D, PlugType.E),
            ["CI"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E),
            ["DJ"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E),
            ["EG"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F),
            ["GQ"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E),
            ["ER"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.L),
            ["SZ"] = new ElectricalSystem(230, 50, PlugType.M),
            ["ET"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E, PlugType.F, PlugType.L),
            ["GA"] = new ElectricalSystem(220, 50, PlugType.C),
            ["GM"] = new ElectricalSystem(230, 50, PlugType.G),
            ["GH"] = new ElectricalSystem(230, 50, PlugType.D, PlugType.G),
            ["GN"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F, PlugType.K),
            ["GW"] = new ElectricalSystem(220, 50, PlugType.C),
            ["KE"] = new ElectricalSystem(240, 50, PlugType.G),
            ["LS"] = new ElectricalSystem(220, 50, PlugType.M),
            ["LR"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["LY"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D, PlugType.F, PlugType.L),
            ["MG"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E),
            ["MW"] = new ElectricalSystem(230, 50, PlugType.G),
            ["ML"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E),
            ["MR"] = new ElectricalSystem(220, 50, PlugType.C),
            ["MU"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.G),
            ["MA"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E),
            ["MZ"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F, PlugType.M),
            ["NA"] = new ElectricalSystem(220, 50, PlugType.D, PlugType.M),
            ["NE"] = new ElectricalSystem(220, 50, PlugType.A, PlugType.B, PlugType.C, PlugType.D, PlugType.E, PlugType.F),
            ["NG"] = new ElectricalSystem(230, 50, PlugType.D, PlugType.G),
            ["RW"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.J),
            ["ST"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F),
            ["SN"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D, PlugType.E, PlugType.K),
            ["SC"] = new ElectricalSystem(240, 50, PlugType.G),
            ["SL"] = new ElectricalSystem(230, 50, PlugType.D, PlugType.G),
            ["SO"] = new ElectricalSystem(220, 50, PlugType.C),
            ["ZA"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D, PlugType.M, PlugType.N),
            ["SS"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D),
            ["SD"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D),
            ["TZ"] = new ElectricalSystem(230, 50, PlugType.D, PlugType.G),
            ["TG"] = new ElectricalSystem(220, 50, PlugType.C),
            ["TN"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.E),
            ["UG"] = new ElectricalSystem(240, 50, PlugType.G),
            ["ZM"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D, PlugType.G),
            ["ZW"] = new ElectricalSystem(220, 50, PlugType.D, PlugType.G),

            // ── Americas ──────────────────────────────────────────────────
            ["AG"] = new ElectricalSystem(230, 60, PlugType.A, PlugType.B),
            ["AR"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.I),
            ["BS"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["BB"] = new ElectricalSystem(115, 50, PlugType.A, PlugType.B),
            ["BZ"] = new ElectricalSystem(110, 60, PlugType.A, PlugType.B, PlugType.G),
            ["BO"] = new ElectricalSystem(230, 50, PlugType.A, PlugType.C),
            ["BR"] = new ElectricalSystem(127, 60, PlugType.C, PlugType.N),
            ["CA"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["CL"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.L),
            ["CO"] = new ElectricalSystem(110, 60, PlugType.A, PlugType.B),
            ["CR"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["CU"] = new ElectricalSystem(110, 60, PlugType.A, PlugType.B, PlugType.C, PlugType.L),
            ["DM"] = new ElectricalSystem(230, 50, PlugType.D, PlugType.G),
            ["DO"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["EC"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["SV"] = new ElectricalSystem(115, 60, PlugType.A, PlugType.B),
            ["GD"] = new ElectricalSystem(230, 50, PlugType.G),
            ["GT"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["GY"] = new ElectricalSystem(240, 60, PlugType.A, PlugType.B, PlugType.D, PlugType.G),
            ["HT"] = new ElectricalSystem(110, 60, PlugType.A, PlugType.B),
            ["HN"] = new ElectricalSystem(110, 60, PlugType.A, PlugType.B),
            ["JM"] = new ElectricalSystem(110, 50, PlugType.A, PlugType.B),
            ["MX"] = new ElectricalSystem(127, 60, PlugType.A, PlugType.B),
            ["NI"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["PA"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["PY"] = new ElectricalSystem(220, 50, PlugType.C),
            ["PE"] = new ElectricalSystem(220, 60, PlugType.A, PlugType.B, PlugType.C),
            ["KN"] = new ElectricalSystem(230, 60, PlugType.D, PlugType.G),
            ["LC"] = new ElectricalSystem(240, 50, PlugType.G),
            ["VC"] = new ElectricalSystem(230, 50, PlugType.A, PlugType.C, PlugType.E, PlugType.G, PlugType.I, PlugType.K),
            ["SR"] = new ElectricalSystem(127, 60, PlugType.A, PlugType.B, PlugType.C, PlugType.F),
            ["TT"] = new ElectricalSystem(115, 60, PlugType.A, PlugType.B),
            ["US"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["UY"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F, PlugType.I, PlugType.L),
            ["VE"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),

            // ── Oceania ───────────────────────────────────────────────────
            ["AU"] = new ElectricalSystem(230, 50, PlugType.I),
            ["FJ"] = new ElectricalSystem(240, 50, PlugType.I),
            ["KI"] = new ElectricalSystem(240, 50, PlugType.I),
            ["MH"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["FM"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["NR"] = new ElectricalSystem(240, 50, PlugType.I),
            ["NZ"] = new ElectricalSystem(230, 50, PlugType.I),
            ["PW"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["PG"] = new ElectricalSystem(240, 50, PlugType.I),
            ["WS"] = new ElectricalSystem(230, 50, PlugType.I),
            ["SB"] = new ElectricalSystem(220, 50, PlugType.G, PlugType.I),
            ["TO"] = new ElectricalSystem(240, 50, PlugType.I),
            ["TV"] = new ElectricalSystem(220, 50, PlugType.I),
            ["VU"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.G, PlugType.I),

            // ── Territories ───────────────────────────────────────────────
            ["HK"] = new ElectricalSystem(220, 50, PlugType.G),
            ["MO"] = new ElectricalSystem(220, 50, PlugType.D, PlugType.G, PlugType.M, PlugType.F),
            ["PR"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["GU"] = new ElectricalSystem(110, 60, PlugType.A, PlugType.B),
            ["VI"] = new ElectricalSystem(110, 60, PlugType.A, PlugType.B),
            ["AQ"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F, PlugType.I),
            ["AI"] = new ElectricalSystem(110, 60, PlugType.A, PlugType.B),
            ["AW"] = new ElectricalSystem(127, 60, PlugType.A, PlugType.B, PlugType.F),
            ["AX"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["BL"] = new ElectricalSystem(230, 60, PlugType.C, PlugType.E),
            ["BM"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["BQ"] = new ElectricalSystem(127, 50, PlugType.A, PlugType.B),
            ["CC"] = new ElectricalSystem(230, 50, PlugType.I),
            ["CK"] = new ElectricalSystem(240, 50, PlugType.I),
            ["CW"] = new ElectricalSystem(127, 50, PlugType.A, PlugType.B),
            ["CX"] = new ElectricalSystem(230, 50, PlugType.I),
            ["EH"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E),
            ["FK"] = new ElectricalSystem(240, 50, PlugType.G),
            ["FO"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.E, PlugType.F, PlugType.K),
            ["GF"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.D, PlugType.E),
            ["GG"] = new ElectricalSystem(230, 50, PlugType.G),
            ["GI"] = new ElectricalSystem(230, 50, PlugType.G),
            ["GL"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F, PlugType.K),
            ["GP"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D, PlugType.E),
            ["GS"] = new ElectricalSystem(230, 50, PlugType.G),
            ["IM"] = new ElectricalSystem(230, 50, PlugType.G),
            ["IO"] = new ElectricalSystem(230, 50, PlugType.G),
            ["JE"] = new ElectricalSystem(230, 50, PlugType.G),
            ["KY"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["MF"] = new ElectricalSystem(230, 60, PlugType.C, PlugType.E),
            ["MP"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["MQ"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.D, PlugType.E),
            ["MS"] = new ElectricalSystem(230, 60, PlugType.A, PlugType.B),
            ["NC"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.F),
            ["NF"] = new ElectricalSystem(230, 50, PlugType.I),
            ["NU"] = new ElectricalSystem(230, 50, PlugType.I),
            ["PF"] = new ElectricalSystem(220, 60, PlugType.A, PlugType.B, PlugType.E),
            ["PM"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.E),
            ["PN"] = new ElectricalSystem(230, 50, PlugType.I),
            ["RE"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.E),
            ["SH"] = new ElectricalSystem(230, 50, PlugType.G),
            ["SJ"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.F),
            ["SX"] = new ElectricalSystem(110, 60, PlugType.A, PlugType.B),
            ["TC"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["TK"] = new ElectricalSystem(230, 50, PlugType.I),
            ["UM"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B),
            ["VG"] = new ElectricalSystem(110, 60, PlugType.A, PlugType.B),
            ["WF"] = new ElectricalSystem(220, 50, PlugType.C, PlugType.E),
            ["YT"] = new ElectricalSystem(230, 50, PlugType.C, PlugType.E),
            ["AS"] = new ElectricalSystem(120, 60, PlugType.A, PlugType.B, PlugType.F, PlugType.I),
            ["AN"] = new ElectricalSystem(127, 50, PlugType.A, PlugType.B),
        };
    }
}
