name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.0  # Replace 'x' with the specific version, e.g., 6.0.100

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test with dotnet
        run: dotnet test --no-restore --verbosity normal

      - name: Pack with dotnet
        run: dotnet pack --no-build --configuration Release --output ./artifacts

      - name: Push NuGet package
        run: |
          nuget push ./artifacts/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
