using System.Collections.Generic;

namespace Multiverse.Globalization.Countries;

/// <summary>
/// Provides emergency telephone numbers for all countries.
/// </summary>
public static class EmergencyNumberHelper
{
    private static readonly Dictionary<string, List<string>> _data = InitializeData();

    internal static IReadOnlyList<string> GetEmergencyNumbersForCountry(string alpha2Code)
    {
        if (string.IsNullOrWhiteSpace(alpha2Code))
            return new List<string>();
        return _data.TryGetValue(alpha2Code.ToUpperInvariant(), out var numbers)
            ? numbers.AsReadOnly()
            : new List<string>();
    }

    /// <summary>All emergency number data keyed by country alpha-2 code.</summary>
    public static IReadOnlyDictionary<string, List<string>> All => _data;

    private static Dictionary<string, List<string>> InitializeData()
    {
        return new Dictionary<string, List<string>>
        {
            // ── Asia ──────────────────────────────────────────────────────
            ["AF"] = new List<string> { "119" },
            ["AM"] = new List<string> { "911", "101", "102", "103" },
            ["AZ"] = new List<string> { "112", "101", "102", "103" },
            ["BH"] = new List<string> { "999" },
            ["BD"] = new List<string> { "999" },
            ["BT"] = new List<string> { "112", "113" },
            ["BN"] = new List<string> { "991", "993", "995" },
            ["KH"] = new List<string> { "117", "118", "119" },
            ["CN"] = new List<string> { "110", "119", "120" },
            ["CY"] = new List<string> { "112", "199" },
            ["GE"] = new List<string> { "112" },
            ["IN"] = new List<string> { "112", "100", "101", "102" },
            ["ID"] = new List<string> { "112", "110", "113", "118" },
            ["IR"] = new List<string> { "110", "115", "125" },
            ["IQ"] = new List<string> { "104", "115" },
            ["IL"] = new List<string> { "100", "101", "102" },
            ["JP"] = new List<string> { "110", "119" },
            ["JO"] = new List<string> { "911", "112" },
            ["KZ"] = new List<string> { "112", "101", "102", "103" },
            ["KW"] = new List<string> { "112" },
            ["KG"] = new List<string> { "112", "101", "102", "103" },
            ["LA"] = new List<string> { "1191", "1195" },
            ["LB"] = new List<string> { "112", "140", "175" },
            ["MY"] = new List<string> { "999", "112" },
            ["MV"] = new List<string> { "119" },
            ["MN"] = new List<string> { "102", "103", "105" },
            ["MM"] = new List<string> { "199" },
            ["NP"] = new List<string> { "100", "101", "102" },
            ["KP"] = new List<string> { "119" },
            ["KR"] = new List<string> { "112", "119" },
            ["OM"] = new List<string> { "9999" },
            ["PK"] = new List<string> { "15", "115", "1122" },
            ["PS"] = new List<string> { "101", "102" },
            ["PH"] = new List<string> { "911", "117" },
            ["QA"] = new List<string> { "999" },
            ["SA"] = new List<string> { "911", "997", "998", "999" },
            ["SG"] = new List<string> { "999", "995" },
            ["LK"] = new List<string> { "119", "110" },
            ["SY"] = new List<string> { "112", "110", "113" },
            ["TW"] = new List<string> { "110", "119" },
            ["TJ"] = new List<string> { "112", "101", "102", "103" },
            ["TH"] = new List<string> { "191", "1669" },
            ["TL"] = new List<string> { "112" },
            ["TR"] = new List<string> { "112", "155", "110" },
            ["TM"] = new List<string> { "01", "02", "03" },
            ["AE"] = new List<string> { "999", "998", "997" },
            ["UZ"] = new List<string> { "101", "102", "103" },
            ["VN"] = new List<string> { "113", "114", "115" },
            ["YE"] = new List<string> { "199" },

            // ── Europe ────────────────────────────────────────────────────
            ["AL"] = new List<string> { "112", "127", "128", "129" },
            ["AD"] = new List<string> { "112", "110", "118" },
            ["AT"] = new List<string> { "112", "133", "122", "144" },
            ["BY"] = new List<string> { "112", "101", "102", "103" },
            ["BE"] = new List<string> { "112", "101" },
            ["BA"] = new List<string> { "112", "122", "123", "124" },
            ["BG"] = new List<string> { "112" },
            ["HR"] = new List<string> { "112", "192", "193", "194" },
            ["CZ"] = new List<string> { "112", "150", "155", "158" },
            ["DK"] = new List<string> { "112" },
            ["EE"] = new List<string> { "112" },
            ["FI"] = new List<string> { "112" },
            ["FR"] = new List<string> { "112", "15", "17", "18" },
            ["DE"] = new List<string> { "112", "110" },
            ["GR"] = new List<string> { "112", "100", "166", "199" },
            ["HU"] = new List<string> { "112", "104", "105", "107" },
            ["IS"] = new List<string> { "112" },
            ["IE"] = new List<string> { "112", "999" },
            ["IT"] = new List<string> { "112", "113", "115", "118" },
            ["LV"] = new List<string> { "112", "110", "113" },
            ["LI"] = new List<string> { "112", "117", "118", "144" },
            ["LT"] = new List<string> { "112" },
            ["LU"] = new List<string> { "112", "113" },
            ["MT"] = new List<string> { "112" },
            ["MD"] = new List<string> { "112", "901", "902", "903" },
            ["MC"] = new List<string> { "112", "17", "18" },
            ["ME"] = new List<string> { "112", "122", "123", "124" },
            ["NL"] = new List<string> { "112" },
            ["MK"] = new List<string> { "112", "192", "193", "194" },
            ["NO"] = new List<string> { "112", "110", "113" },
            ["PL"] = new List<string> { "112", "997", "998", "999" },
            ["PT"] = new List<string> { "112" },
            ["RO"] = new List<string> { "112" },
            ["RU"] = new List<string> { "112", "01", "02", "03" },
            ["SM"] = new List<string> { "112", "113" },
            ["RS"] = new List<string> { "112", "192", "193", "194" },
            ["SK"] = new List<string> { "112", "150", "155", "158" },
            ["SI"] = new List<string> { "112", "113" },
            ["ES"] = new List<string> { "112" },
            ["SE"] = new List<string> { "112" },
            ["CH"] = new List<string> { "112", "117", "118", "144" },
            ["UA"] = new List<string> { "112", "101", "102", "103" },
            ["GB"] = new List<string> { "999", "112" },
            ["VA"] = new List<string> { "112" },

            // ── Africa ────────────────────────────────────────────────────
            ["DZ"] = new List<string> { "14", "17", "1021" },
            ["AO"] = new List<string> { "113", "115" },
            ["BJ"] = new List<string> { "117", "118" },
            ["BW"] = new List<string> { "999", "997" },
            ["BF"] = new List<string> { "17", "18" },
            ["BI"] = new List<string> { "117" },
            ["CV"] = new List<string> { "132", "131", "130" },
            ["CM"] = new List<string> { "112", "117", "118" },
            ["CF"] = new List<string> { "117", "1220" },
            ["TD"] = new List<string> { "17" },
            ["KM"] = new List<string> { "17", "18" },
            ["CG"] = new List<string> { "117", "118" },
            ["CD"] = new List<string> { "112" },
            ["CI"] = new List<string> { "110", "111", "170", "180" },
            ["DJ"] = new List<string> { "17", "18" },
            ["EG"] = new List<string> { "122", "123", "180" },
            ["GQ"] = new List<string> { "114" },
            ["ER"] = new List<string> { "114", "119" },
            ["SZ"] = new List<string> { "999" },
            ["ET"] = new List<string> { "911", "907", "939" },
            ["GA"] = new List<string> { "1730", "18" },
            ["GM"] = new List<string> { "117", "118" },
            ["GH"] = new List<string> { "191", "192", "193" },
            ["GN"] = new List<string> { "117", "442020" },
            ["GW"] = new List<string> { "117", "119" },
            ["KE"] = new List<string> { "999", "112" },
            ["LS"] = new List<string> { "112", "123", "124" },
            ["LR"] = new List<string> { "911" },
            ["LY"] = new List<string> { "1515", "193" },
            ["MG"] = new List<string> { "117", "118" },
            ["MW"] = new List<string> { "997", "998", "999" },
            ["ML"] = new List<string> { "17", "18" },
            ["MR"] = new List<string> { "17", "101" },
            ["MU"] = new List<string> { "999", "112" },
            ["MA"] = new List<string> { "190", "150", "15" },
            ["MZ"] = new List<string> { "112", "119" },
            ["NA"] = new List<string> { "10111" },
            ["NE"] = new List<string> { "17", "18" },
            ["NG"] = new List<string> { "112", "199" },
            ["RW"] = new List<string> { "112" },
            ["ST"] = new List<string> { "112" },
            ["SN"] = new List<string> { "17", "18" },
            ["SC"] = new List<string> { "999" },
            ["SL"] = new List<string> { "019", "999" },
            ["SO"] = new List<string> { "888", "999" },
            ["ZA"] = new List<string> { "10111", "112" },
            ["SS"] = new List<string> { "999" },
            ["SD"] = new List<string> { "999" },
            ["TZ"] = new List<string> { "112", "114" },
            ["TG"] = new List<string> { "117", "118" },
            ["TN"] = new List<string> { "190", "197", "198" },
            ["UG"] = new List<string> { "999", "112" },
            ["ZM"] = new List<string> { "999", "112" },
            ["ZW"] = new List<string> { "999", "112" },

            // ── Americas ──────────────────────────────────────────────────
            ["AG"] = new List<string> { "911", "999" },
            ["AR"] = new List<string> { "911", "100", "101", "107" },
            ["BS"] = new List<string> { "911", "919" },
            ["BB"] = new List<string> { "211", "511" },
            ["BZ"] = new List<string> { "911", "90" },
            ["BO"] = new List<string> { "110", "118", "119" },
            ["BR"] = new List<string> { "190", "192", "193" },
            ["CA"] = new List<string> { "911" },
            ["CL"] = new List<string> { "131", "132", "133" },
            ["CO"] = new List<string> { "123" },
            ["CR"] = new List<string> { "911" },
            ["CU"] = new List<string> { "106", "105", "104" },
            ["DM"] = new List<string> { "999" },
            ["DO"] = new List<string> { "911" },
            ["EC"] = new List<string> { "911" },
            ["SV"] = new List<string> { "911" },
            ["GD"] = new List<string> { "911" },
            ["GT"] = new List<string> { "110", "120", "123" },
            ["GY"] = new List<string> { "911", "912", "913" },
            ["HT"] = new List<string> { "114", "115", "116" },
            ["HN"] = new List<string> { "911", "199" },
            ["JM"] = new List<string> { "119", "110" },
            ["MX"] = new List<string> { "911" },
            ["NI"] = new List<string> { "118" },
            ["PA"] = new List<string> { "911" },
            ["PY"] = new List<string> { "911" },
            ["PE"] = new List<string> { "105", "116", "117" },
            ["KN"] = new List<string> { "911" },
            ["LC"] = new List<string> { "911", "999" },
            ["VC"] = new List<string> { "911", "999" },
            ["SR"] = new List<string> { "115" },
            ["TT"] = new List<string> { "999", "990" },
            ["US"] = new List<string> { "911" },
            ["UY"] = new List<string> { "911" },
            ["VE"] = new List<string> { "911", "171" },

            // ── Oceania ───────────────────────────────────────────────────
            ["AU"] = new List<string> { "000", "112" },
            ["FJ"] = new List<string> { "911", "917" },
            ["KI"] = new List<string> { "992", "994" },
            ["MH"] = new List<string> { "911" },
            ["FM"] = new List<string> { "911" },
            ["NR"] = new List<string> { "110", "111" },
            ["NZ"] = new List<string> { "111" },
            ["PW"] = new List<string> { "911" },
            ["PG"] = new List<string> { "000" },
            ["WS"] = new List<string> { "999" },
            ["SB"] = new List<string> { "999" },
            ["TO"] = new List<string> { "911", "922", "933" },
            ["TV"] = new List<string> { "911" },
            ["VU"] = new List<string> { "112" },

            // ── Territories ───────────────────────────────────────────────
            ["HK"] = new List<string> { "999" },
            ["MO"] = new List<string> { "999" },
            ["PR"] = new List<string> { "911" },
            ["GU"] = new List<string> { "911" },
            ["VI"] = new List<string> { "911" },
            ["AQ"] = new List<string> { "112" },
            ["AI"] = new List<string> { "911" },
            ["AW"] = new List<string> { "911", "100" },
            ["AX"] = new List<string> { "112" },
            ["BL"] = new List<string> { "15", "17", "18" },
            ["BM"] = new List<string> { "911" },
            ["BQ"] = new List<string> { "911", "112" },
            ["CC"] = new List<string> { "000" },
            ["CK"] = new List<string> { "999" },
            ["CW"] = new List<string> { "911", "112" },
            ["CX"] = new List<string> { "000" },
            ["EH"] = new List<string> { "190", "150", "15" },
            ["FK"] = new List<string> { "999" },
            ["FO"] = new List<string> { "112" },
            ["GF"] = new List<string> { "15", "17", "18" },
            ["GG"] = new List<string> { "999", "112" },
            ["GI"] = new List<string> { "112", "199" },
            ["GL"] = new List<string> { "112" },
            ["GP"] = new List<string> { "15", "17", "18" },
            ["GS"] = new List<string> { "112" },
            ["HM"] = new List<string> { "000" },
            ["IM"] = new List<string> { "999", "112" },
            ["IO"] = new List<string> { "999" },
            ["JE"] = new List<string> { "999", "112" },
            ["KY"] = new List<string> { "911" },
            ["MF"] = new List<string> { "15", "17", "18" },
            ["MP"] = new List<string> { "911" },
            ["MQ"] = new List<string> { "15", "17", "18" },
            ["MS"] = new List<string> { "999", "911" },
            ["NC"] = new List<string> { "15", "17", "18" },
            ["NF"] = new List<string> { "000" },
            ["NU"] = new List<string> { "999" },
            ["PF"] = new List<string> { "15", "17", "18" },
            ["PM"] = new List<string> { "15", "17", "18" },
            ["PN"] = new List<string> { "112" },
            ["RE"] = new List<string> { "15", "17", "18" },
            ["SH"] = new List<string> { "999" },
            ["SJ"] = new List<string> { "112", "110", "113" },
            ["SX"] = new List<string> { "911", "112" },
            ["TC"] = new List<string> { "911", "999" },
            ["TF"] = new List<string> { "112" },
            ["TK"] = new List<string> { "911" },
            ["UM"] = new List<string> { "911" },
            ["VG"] = new List<string> { "999", "911" },
            ["WF"] = new List<string> { "15", "17", "18" },
            ["YT"] = new List<string> { "15", "17", "18" },
            ["AS"] = new List<string> { "911" },
            ["AN"] = new List<string> { "911", "112" },
            ["BV"] = new List<string> { "112" },
        };
    }
}
