using System.Collections.Generic;

namespace Multiverse.Globalization.Countries;

/// <summary>
/// Provides phone number format data for countries.
/// </summary>
public static class PhoneFormatHelper
{
    private static readonly Dictionary<string, PhoneFormat> _data = InitializeData();

    internal static PhoneFormat? GetPhoneFormatForCountry(string alpha2Code)
    {
        if (string.IsNullOrWhiteSpace(alpha2Code))
            return null;
        return _data.TryGetValue(alpha2Code.ToUpperInvariant(), out var format) ? format : null;
    }

    /// <summary>All phone format data keyed by country alpha-2 code.</summary>
    public static IReadOnlyDictionary<string, PhoneFormat> All => _data;

    private static Dictionary<string, PhoneFormat> InitializeData()
    {
        return new Dictionary<string, PhoneFormat>
        {
            // ── Americas ──────────────────────────────────────────────────
            ["US"] = new PhoneFormat(10, 10, "1", "011"),
            ["CA"] = new PhoneFormat(10, 10, "1", "011"),
            ["MX"] = new PhoneFormat(10, 10, "", "00"),
            ["BR"] = new PhoneFormat(10, 11, "0", "00"),
            ["AR"] = new PhoneFormat(10, 10, "0", "00"),
            ["CO"] = new PhoneFormat(10, 10, "", "00"),
            ["CL"] = new PhoneFormat(9, 9, "", "00"),
            ["PE"] = new PhoneFormat(9, 9, "0", "00"),
            ["VE"] = new PhoneFormat(10, 10, "0", "00"),
            ["EC"] = new PhoneFormat(9, 9, "0", "00"),
            ["BO"] = new PhoneFormat(8, 8, "0", "00"),
            ["PY"] = new PhoneFormat(9, 10, "0", "00"),
            ["UY"] = new PhoneFormat(8, 8, "0", "00"),
            ["GY"] = new PhoneFormat(7, 7, "", "001"),
            ["SR"] = new PhoneFormat(7, 7, "", "00"),
            ["AG"] = new PhoneFormat(10, 10, "1", "011"),
            ["BS"] = new PhoneFormat(10, 10, "1", "011"),
            ["BB"] = new PhoneFormat(10, 10, "1", "011"),
            ["BZ"] = new PhoneFormat(7, 7, "", "00"),
            ["CR"] = new PhoneFormat(8, 8, "", "00"),
            ["CU"] = new PhoneFormat(8, 8, "0", "119"),
            ["DM"] = new PhoneFormat(10, 10, "1", "011"),
            ["DO"] = new PhoneFormat(10, 10, "1", "011"),
            ["SV"] = new PhoneFormat(8, 8, "", "00"),
            ["GD"] = new PhoneFormat(10, 10, "1", "011"),
            ["GT"] = new PhoneFormat(8, 8, "", "00"),
            ["HT"] = new PhoneFormat(8, 8, "", "00"),
            ["HN"] = new PhoneFormat(8, 8, "", "00"),
            ["JM"] = new PhoneFormat(10, 10, "1", "011"),
            ["NI"] = new PhoneFormat(8, 8, "", "00"),
            ["PA"] = new PhoneFormat(7, 8, "", "00"),
            ["KN"] = new PhoneFormat(10, 10, "1", "011"),
            ["LC"] = new PhoneFormat(10, 10, "1", "011"),
            ["VC"] = new PhoneFormat(10, 10, "1", "011"),
            ["TT"] = new PhoneFormat(10, 10, "1", "011"),

            // ── Europe ────────────────────────────────────────────────────
            ["GB"] = new PhoneFormat(10, 11, "0", "00"),
            ["DE"] = new PhoneFormat(6, 12, "0", "00"),
            ["FR"] = new PhoneFormat(9, 9, "0", "00"),
            ["IT"] = new PhoneFormat(6, 11, "", "00"),
            ["ES"] = new PhoneFormat(9, 9, "", "00"),
            ["PT"] = new PhoneFormat(9, 9, "", "00"),
            ["NL"] = new PhoneFormat(9, 9, "0", "00"),
            ["BE"] = new PhoneFormat(8, 9, "0", "00"),
            ["CH"] = new PhoneFormat(9, 9, "0", "00"),
            ["AT"] = new PhoneFormat(4, 13, "0", "00"),
            ["SE"] = new PhoneFormat(7, 9, "0", "00"),
            ["NO"] = new PhoneFormat(8, 8, "", "00"),
            ["DK"] = new PhoneFormat(8, 8, "", "00"),
            ["FI"] = new PhoneFormat(5, 12, "0", "00"),
            ["PL"] = new PhoneFormat(9, 9, "", "00"),
            ["CZ"] = new PhoneFormat(9, 9, "", "00"),
            ["HU"] = new PhoneFormat(8, 9, "06", "00"),
            ["RO"] = new PhoneFormat(9, 9, "0", "00"),
            ["GR"] = new PhoneFormat(10, 10, "", "00"),
            ["IE"] = new PhoneFormat(7, 9, "0", "00"),
            ["RU"] = new PhoneFormat(10, 10, "8", "810"),
            ["UA"] = new PhoneFormat(9, 9, "0", "00"),
            ["TR"] = new PhoneFormat(10, 10, "0", "00"),
            ["AL"] = new PhoneFormat(9, 9, "0", "00"),
            ["AD"] = new PhoneFormat(6, 9, "", "00"),
            ["BY"] = new PhoneFormat(10, 10, "80", "810"),
            ["BA"] = new PhoneFormat(8, 8, "0", "00"),
            ["BG"] = new PhoneFormat(8, 9, "0", "00"),
            ["HR"] = new PhoneFormat(8, 9, "0", "00"),
            ["EE"] = new PhoneFormat(7, 8, "", "00"),
            ["IS"] = new PhoneFormat(7, 7, "", "00"),
            ["LV"] = new PhoneFormat(8, 8, "", "00"),
            ["LI"] = new PhoneFormat(7, 7, "", "00"),
            ["LT"] = new PhoneFormat(8, 8, "8", "00"),
            ["LU"] = new PhoneFormat(6, 9, "", "00"),
            ["MT"] = new PhoneFormat(8, 8, "", "00"),
            ["MD"] = new PhoneFormat(8, 8, "0", "00"),
            ["MC"] = new PhoneFormat(8, 8, "", "00"),
            ["ME"] = new PhoneFormat(8, 8, "0", "00"),
            ["MK"] = new PhoneFormat(8, 8, "0", "00"),
            ["RS"] = new PhoneFormat(8, 9, "0", "00"),
            ["SK"] = new PhoneFormat(9, 9, "0", "00"),
            ["SI"] = new PhoneFormat(8, 8, "0", "00"),
            ["SM"] = new PhoneFormat(6, 10, "", "00"),
            ["VA"] = new PhoneFormat(6, 11, "", "00"),

            // ── Asia ──────────────────────────────────────────────────────
            ["JP"] = new PhoneFormat(10, 10, "0", "010"),
            ["CN"] = new PhoneFormat(11, 11, "0", "00"),
            ["IN"] = new PhoneFormat(10, 10, "0", "00"),
            ["KR"] = new PhoneFormat(9, 11, "0", "001"),
            ["PK"] = new PhoneFormat(10, 10, "0", "00"),
            ["BD"] = new PhoneFormat(10, 10, "0", "00"),
            ["ID"] = new PhoneFormat(9, 12, "0", "001"),
            ["PH"] = new PhoneFormat(10, 10, "0", "00"),
            ["VN"] = new PhoneFormat(9, 10, "0", "00"),
            ["TH"] = new PhoneFormat(9, 9, "0", "001"),
            ["MY"] = new PhoneFormat(9, 10, "0", "00"),
            ["SG"] = new PhoneFormat(8, 8, "", "001"),
            ["SA"] = new PhoneFormat(9, 9, "0", "00"),
            ["AE"] = new PhoneFormat(9, 9, "0", "00"),
            ["IL"] = new PhoneFormat(9, 9, "0", "00"),
            ["IR"] = new PhoneFormat(10, 10, "0", "00"),
            ["IQ"] = new PhoneFormat(10, 10, "0", "00"),
            ["AF"] = new PhoneFormat(9, 9, "0", "00"),
            ["AM"] = new PhoneFormat(8, 8, "0", "00"),
            ["AZ"] = new PhoneFormat(9, 9, "0", "00"),
            ["BH"] = new PhoneFormat(8, 8, "", "00"),
            ["BT"] = new PhoneFormat(8, 8, "", "00"),
            ["BN"] = new PhoneFormat(7, 7, "", "00"),
            ["KH"] = new PhoneFormat(8, 9, "0", "001"),
            ["CY"] = new PhoneFormat(8, 8, "", "00"),
            ["GE"] = new PhoneFormat(9, 9, "", "00"),
            ["JO"] = new PhoneFormat(9, 9, "0", "00"),
            ["KZ"] = new PhoneFormat(10, 10, "8", "810"),
            ["KW"] = new PhoneFormat(8, 8, "", "00"),
            ["KG"] = new PhoneFormat(9, 9, "0", "00"),
            ["LA"] = new PhoneFormat(8, 10, "0", "00"),
            ["LB"] = new PhoneFormat(7, 8, "0", "00"),
            ["MV"] = new PhoneFormat(7, 7, "", "00"),
            ["MN"] = new PhoneFormat(8, 8, "0", "001"),
            ["MM"] = new PhoneFormat(7, 10, "0", "00"),
            ["NP"] = new PhoneFormat(10, 10, "0", "00"),
            ["KP"] = new PhoneFormat(8, 8, "0", "00"),
            ["OM"] = new PhoneFormat(8, 8, "", "00"),
            ["QA"] = new PhoneFormat(8, 8, "", "00"),
            ["PS"] = new PhoneFormat(9, 9, "0", "00"),
            ["LK"] = new PhoneFormat(9, 9, "0", "00"),
            ["SY"] = new PhoneFormat(9, 9, "0", "00"),
            ["TW"] = new PhoneFormat(9, 9, "0", "002"),
            ["TJ"] = new PhoneFormat(9, 9, "8", "810"),
            ["TL"] = new PhoneFormat(7, 8, "", "00"),
            ["TM"] = new PhoneFormat(8, 8, "8", "810"),
            ["UZ"] = new PhoneFormat(9, 9, "0", "810"),
            ["YE"] = new PhoneFormat(9, 9, "0", "00"),

            // ── Africa ────────────────────────────────────────────────────
            ["EG"] = new PhoneFormat(10, 10, "0", "00"),
            ["ZA"] = new PhoneFormat(9, 9, "0", "00"),
            ["NG"] = new PhoneFormat(10, 10, "0", "009"),
            ["KE"] = new PhoneFormat(9, 9, "0", "000"),
            ["DZ"] = new PhoneFormat(9, 9, "0", "00"),
            ["AO"] = new PhoneFormat(9, 9, "", "00"),
            ["BJ"] = new PhoneFormat(8, 8, "", "00"),
            ["BW"] = new PhoneFormat(7, 8, "", "00"),
            ["BF"] = new PhoneFormat(8, 8, "", "00"),
            ["BI"] = new PhoneFormat(8, 8, "", "00"),
            ["CV"] = new PhoneFormat(7, 7, "", "0"),
            ["CM"] = new PhoneFormat(9, 9, "", "00"),
            ["CF"] = new PhoneFormat(8, 8, "", "00"),
            ["TD"] = new PhoneFormat(8, 8, "", "00"),
            ["KM"] = new PhoneFormat(7, 7, "", "00"),
            ["CG"] = new PhoneFormat(9, 9, "", "00"),
            ["CD"] = new PhoneFormat(9, 9, "0", "00"),
            ["CI"] = new PhoneFormat(10, 10, "", "00"),
            ["DJ"] = new PhoneFormat(8, 8, "", "00"),
            ["GQ"] = new PhoneFormat(9, 9, "", "00"),
            ["ER"] = new PhoneFormat(7, 7, "0", "00"),
            ["ET"] = new PhoneFormat(9, 9, "0", "00"),
            ["SZ"] = new PhoneFormat(8, 8, "", "00"),
            ["GA"] = new PhoneFormat(7, 8, "", "00"),
            ["GM"] = new PhoneFormat(7, 7, "", "00"),
            ["GH"] = new PhoneFormat(9, 9, "0", "00"),
            ["GN"] = new PhoneFormat(8, 9, "", "00"),
            ["GW"] = new PhoneFormat(7, 7, "", "00"),
            ["LS"] = new PhoneFormat(8, 8, "", "00"),
            ["LR"] = new PhoneFormat(7, 8, "", "00"),
            ["LY"] = new PhoneFormat(9, 10, "0", "00"),
            ["MG"] = new PhoneFormat(9, 10, "0", "00"),
            ["MW"] = new PhoneFormat(9, 9, "", "00"),
            ["ML"] = new PhoneFormat(8, 8, "", "00"),
            ["MR"] = new PhoneFormat(8, 8, "", "00"),
            ["MU"] = new PhoneFormat(8, 8, "", "020"),
            ["MA"] = new PhoneFormat(9, 9, "0", "00"),
            ["MZ"] = new PhoneFormat(9, 9, "", "00"),
            ["NA"] = new PhoneFormat(9, 10, "0", "00"),
            ["NE"] = new PhoneFormat(8, 8, "", "00"),
            ["RW"] = new PhoneFormat(9, 9, "0", "00"),
            ["ST"] = new PhoneFormat(7, 7, "", "00"),
            ["SN"] = new PhoneFormat(9, 9, "", "00"),
            ["SC"] = new PhoneFormat(7, 7, "", "00"),
            ["SL"] = new PhoneFormat(8, 8, "0", "00"),
            ["SO"] = new PhoneFormat(7, 8, "", "00"),
            ["SS"] = new PhoneFormat(9, 9, "0", "00"),
            ["SD"] = new PhoneFormat(9, 9, "0", "00"),
            ["TZ"] = new PhoneFormat(9, 9, "0", "000"),
            ["TG"] = new PhoneFormat(8, 8, "", "00"),
            ["TN"] = new PhoneFormat(8, 8, "", "00"),
            ["UG"] = new PhoneFormat(9, 9, "0", "000"),
            ["ZM"] = new PhoneFormat(9, 9, "0", "00"),
            ["ZW"] = new PhoneFormat(9, 9, "0", "00"),

            // ── Oceania ───────────────────────────────────────────────────
            ["AU"] = new PhoneFormat(9, 9, "0", "0011"),
            ["NZ"] = new PhoneFormat(8, 10, "0", "00"),
            ["FJ"] = new PhoneFormat(7, 7, "", "00"),
            ["KI"] = new PhoneFormat(5, 8, "", "00"),
            ["MH"] = new PhoneFormat(7, 7, "1", "011"),
            ["FM"] = new PhoneFormat(7, 7, "1", "011"),
            ["NR"] = new PhoneFormat(7, 7, "", "00"),
            ["PW"] = new PhoneFormat(7, 7, "", "011"),
            ["PG"] = new PhoneFormat(7, 8, "", "05"),
            ["WS"] = new PhoneFormat(5, 7, "", "0"),
            ["SB"] = new PhoneFormat(5, 7, "", "00"),
            ["TO"] = new PhoneFormat(5, 7, "", "00"),
            ["TV"] = new PhoneFormat(5, 6, "", "00"),
            ["VU"] = new PhoneFormat(5, 7, "", "00"),

            // ── Territories ───────────────────────────────────────────────
            ["HK"] = new PhoneFormat(8, 8, "", "001"),
            ["MO"] = new PhoneFormat(8, 8, "", "00"),
            ["PR"] = new PhoneFormat(10, 10, "1", "011"),
            ["GU"] = new PhoneFormat(10, 10, "1", "011"),
            ["VI"] = new PhoneFormat(10, 10, "1", "011"),
            ["AS"] = new PhoneFormat(10, 10, "1", "011"),
            ["MP"] = new PhoneFormat(10, 10, "1", "011"),
            ["AI"] = new PhoneFormat(10, 10, "1", "011"),
            ["AW"] = new PhoneFormat(7, 7, "", "00"),
            ["BM"] = new PhoneFormat(10, 10, "1", "011"),
            ["KY"] = new PhoneFormat(10, 10, "1", "011"),
            ["CW"] = new PhoneFormat(7, 8, "", "00"),
            ["FK"] = new PhoneFormat(5, 5, "", "00"),
            ["FO"] = new PhoneFormat(6, 6, "", "00"),
            ["GF"] = new PhoneFormat(9, 9, "0", "00"),
            ["GI"] = new PhoneFormat(8, 8, "", "00"),
            ["GL"] = new PhoneFormat(6, 6, "", "00"),
            ["GP"] = new PhoneFormat(9, 9, "0", "00"),
            ["GG"] = new PhoneFormat(10, 10, "0", "00"),
            ["IM"] = new PhoneFormat(10, 10, "0", "00"),
            ["JE"] = new PhoneFormat(10, 10, "0", "00"),
            ["MQ"] = new PhoneFormat(9, 9, "0", "00"),
            ["MS"] = new PhoneFormat(10, 10, "1", "011"),
            ["NC"] = new PhoneFormat(6, 6, "", "00"),
            ["PF"] = new PhoneFormat(6, 6, "", "00"),
            ["RE"] = new PhoneFormat(9, 9, "0", "00"),
            ["SH"] = new PhoneFormat(4, 4, "", "00"),
            ["PM"] = new PhoneFormat(6, 6, "", "00"),
            ["SX"] = new PhoneFormat(10, 10, "1", "011"),
            ["TC"] = new PhoneFormat(10, 10, "1", "011"),
            ["VG"] = new PhoneFormat(10, 10, "1", "011"),
            ["WF"] = new PhoneFormat(6, 6, "", "00"),
            ["YT"] = new PhoneFormat(9, 9, "0", "00"),
            ["BQ"] = new PhoneFormat(7, 7, "", "00"),
            ["BL"] = new PhoneFormat(9, 9, "0", "00"),
            ["MF"] = new PhoneFormat(9, 9, "0", "00"),
            ["AX"] = new PhoneFormat(5, 12, "0", "00"),
        };
    }
}
